### ISSUE TITLE
Trying to update to version 2.18, unable to start webwork service

### ISSUE THREAD

**Issue by tekjoey** [openwebwork/webwork2#2575]
I am updating from 2.17 to 2.18, and I have gotten all the way to creating and starting the webwork service. However, when I try to start it, I received the following error:

`Can't load application from file "/opt/webwork/webwork2/bin/webwork2": Expected '{' for block body or ';' at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator.pm line 107.
Compilation failed in require at /usr/local/perlbrew/perls/perl-5.22.0/lib/site_perl/5.22.0/Mojo/Base.pm line 132.
BEGIN failed--compilation aborted at /opt/webwork/webwork2/lib/WeBWorK/ContentGenerator/Login.pm line 17.
Compilation failed in require at /opt/webwork/webwork2/lib/WeBWorK.pm line 50.
BEGIN failed--compilation aborted at /opt/webwork/webwork2/lib/WeBWorK.pm line 50.
Compilation failed in require at /opt/webwork/webwork2/lib/Mojolicious/WeBWorK.pm line 27.
BEGIN failed--compilation aborted at /opt/webwork/webwork2/lib/Mojolicious/WeBWorK.pm line 27.
Compilation failed in require at (eval 133) line 1.`

I am running webwork on RedHat 8.10. Please let me know if you need any other information.

**Comment by dlglin** [comment]
This purpose of this space is to report issues with the software itself.  The better place to get help with installation is https://webwork.maa.org/forums/.

Having said that, here are some initial things to check (if you haven't already):

- Run `/opt/webwork/webwork2/bin/check_modules.pl` and check that nothing is missing.
- If you are upgrading from 2.17 to 2.18 (you should probably jump to 2.19 now that it's released), then you should check carefully that all settings in the latest `site.conf.dist` are reflected in your `site.conf`.  The recommended approach is to start from a fresh copy of `site.conf.dist` and copy any settings from your old `site.conf`.
- You can try manually starting the webwork service using `sudo hypnotoad -f /opt/webwork/webwork2/bin/webwork2` to see if you get a more descriptive error (though this may not work due to permission issues).

**Comment by tekjoey** [comment]
@dlglin Thank you for your help, and my apologies for not posting to the forum, I will use it in the future.
